[package]
name = "rocketchat-message"
version = "0.1.2"
edition = "2021"
license = "MIT"
description = "Library to send rocket chat messages"

[dependencies]
serde = { version = "1.0.126", features = ["derive"] }
reqwest = { version = "0.11.4", features = ["json", "blocking"] }
anyhow = "1.0"